const actionTypes = {
  // Check
  REFRESHFE: "REFRESHFE",
  LOADING: "LOADING",

  IDUSER: "IDUSER",
  INFOUSER: "INFOUSER",
  HOME: "HOME",
  ISLOGIN: "ISLOGIN",
  SETROLE: "SETROLE",

  // Lecturer
  DATACALCULATE: "DATACALCULATE",

  // admin
  ISBLUR: "ISBLUR",
  TYPEDELETE: "TYPEDELETE",
  TYPEBLUR: "TYPEBLUR",
  LISTDELETE: "LISTDELETE",
  EDITSTUDENTEXPENSES: "EDITSTUDENTEXPENSES",
  EDITINVOICE: "EDITINVOIC",
  EDITTEACHINGPERIOD: "EDITTEACHINGPERIOD",

  // upload file Excel
  TYPEUPLOAD: "TYPEUPLOAD",
};

export default actionTypes;
