const actionTypes = {
  HOME: "HOME",
  ISLOGIN: "ISLOGIN",
  // admin
  ISBLUR: "ISBLUR",
  TYPEDELETE: "TYPEDELETE",
  TYPEBLUR: "TYPEBLUR",
  LISTDELETE: "LISTDELETE",
  EDITSTUDENTEXPENSES: "EDITSTUDENTEXPENSES",
  EDITINVOICE: "EDITINVOIC",
  EDITTEACHINGPERIOD: "EDITTEACHINGPERIOD",
};

export default actionTypes;
